stages:
  - pull-github
  - build
  - deploy

variables:
  GIT_STRATEGY: clone			#This seems to have no effect also set in webinterface
  GIT_DEPTH: 0					#This seems to have no effect also set in webinterface
  GIT_SUBMODULE_STRATEGY: recursive

pull:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_BRANCH == "master"'
  image: ubuntu:20.04
  tags:
    - docker
  stage: pull-github
  before_script:
    - apt-get install -y git
  script:
    - chmod +x ./ci-scripts/pull.sh
    - ./ci-scripts/pull.sh

build-pypi:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - lxc
  stage: build
  script:
    - make CI
  artifacts:
    paths:
      - dist/*

build-msi:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - lxc
  stage: build
  script:
    - make wine-build
  artifacts:
    paths:
      - wine-build/*.exe
      - wine-build/*.msi

upload-nightly:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - docker
  image: nightly-upload:latest
  before_script:
    - apt-get update -y
    - apt-get install -y git zip rsync
  script:
    - chmod +x ./ci-scripts/nightly_upload.sh
    - mkdir nightly-build
    - mv wine-build/*.msi nightly-build
    - mv wine-build/*.exe nightly-build
    - mv dist/* nightly-build
    - zip -r pynitrokey.zip nightly-build
    - ./ci-scripts/nightly_upload.sh pynitrokey.zip

build-and-publish-pypi:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  tags:
    - lxc
  stage: build
  script:
    - make CI
    - sed -e "s|\${passw}|$PYPI_TOKEN|" ci-scripts/.pypirc_tamplate > ~/.pypirc
    - make publish

publish-msi:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
  image: ubuntu:20.04
  tags:
    - docker
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y git curl jq zip
    - chmod +x ./ci-scripts/release.sh
    - ./ci-scripts/release.sh