version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build-msi-win:
    executor: win/default
    steps:
      - checkout
      - run: pip install -r ci-requirements.txt
      - run: python win_setup.py bdist_msi

  build-linux:
    executor: python/default
    steps:
      - checkout
      - run: make init
      - run: make CI

  install-test-pip:
    executor: python/default
    steps:
      - checkout
      - run: make system-pip-install-test
      - run: make system-pip-uninstall
      - run: make system-pip-install-test
      - run: make system-pip-install-test
      - run: make system-pip-uninstall

  install-with-older-fido:
    executor: python/default
    steps:
      - checkout
      - run: python -m pip install fido==0.7.2
      - run: python -m pip install pynitrokey
      - run: nitropy 

workflows:
  main:
    jobs:
      - build-msi-win
      - build-linux
      - install-test-pip
      - install-with-older-fido
